### PR TITLE
Add support for PHP 8.2, Remove support for PHP 7.4

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### CODE REVIEW

**Comment by gsteel** [comment]
Needs https://github.com/laminas/laminas-httphandlerrunner/pull/33

**Comment by Ocramius** [comment]
@gsteel done

**Comment by gsteel** [comment]
Thanks @Ocramius - I'll get the others done first so we don't have to ignore platform reqs here

**Review by Ocramius — APPROVED** [review]
CI doesn't ignore platform requirements here, so we can :ship:

**Comment by Ocramius** [comment]
Ah, nope, still red :-\

**Comment by gsteel** [comment]
There's still a couple of deps to go and a lock refresh. Just done https://github.com/mezzio/mezzio-fastroute/pull/24

**Comment by gsteel** [comment]
All green now @Ocramius - had to ignore platform reqs because of `laminas-http` 🤷‍♂️

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @gsteel!

**Pull request merged**
