### PR TITLE
Fix FQDN

### PR DESCRIPTION
**Pull request by Maks3w**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by Maks3w** [comment]
Signed-Off is PITA if you just want to make a quickfix through GitHub web editor

**Comment by weierophinney** [comment]
> Signed-Off is PITA if you just want to make a quickfix through GitHub web editor

You can add the sign-off _in the commit message_ in the format:

```text
Signed-Off-By: {full name}<email>
```

I'd consider this to fall under our "Obvious Fix Policy" however, and I'll set the DCO to pass.

**Comment by Ocramius** [comment]
@Maks3w DCO is indeed a pain, and it's on my list of "things to die for on a shallow hill", for the next TSC meeting

**Comment by Ocramius** [comment]
@Maks3w https://github.com/laminas/technical-steering-committee/pull/60

**Pull request merged**
