### PR TITLE
PHP 8.0 compatiblity and dependency upgrades.

### PR DESCRIPTION
**Pull request by jensdenies**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

This pull requests aims to make Mezzio PHP 8.0 compatible. I've bumped the dependencies to the **lowest** version that supports PHP 7.3 up until 8.0.

### CODE REVIEW

**Comment by jensdenies** [comment]
@lcobucci Tests seem to pass. 😃 

`mezzio/mezzio-aurarouter` and `mezzio/mezzio-template` do not seem to have a PHP 8 compatible release yet (there are open PRs for that), that's why I had to ignore platform requirements in Travis.

**Comment by jensdenies** [comment]
Hi @boesing, @lcobucci, would you prefer holding this off until the PHP 8 upgrades for mezzio-template and mezzio-aurarouter are completed? 😀

**Comment by acelaya** [comment]
The one for mezzio-template has just been merged by @samsonasik and he released v2.1, so only aurarouter one is missing now.

**Comment by jensdenies** [comment]
@acelaya I've updated the dependency, thanks for notifying me! 👍

**Comment by lcobucci** [comment]
Sorry @jensdenies I had a crazy busy week. It looks good to me and I don't think we must wait for the other packages. The only thing we're missing here is the cleanup of the compatibility layer on whoops (the code and the phpstan config have some stuff for whoops v1).

**Comment by jensdenies** [comment]
@lcobucci No worries! I'll take a look! 😀

**Comment by jensdenies** [comment]
@lcobucci I've removed the obsolete code. 👍

**Comment by Ocramius** [comment]
Deferred removal of `--ignore-platform-reqs` to #62

**Review by Ocramius — APPROVED** [review]
🚢

**Comment by jensdenies** [comment]
Thanks @Ocramius and @lcobucci!

**Comment by jensdenies** [comment]
@Ocramius @lcobucci  I just realized, the dependency upgrade wasn't actually necessary, right? Because Composer would've pulled the correct version anyway if there was a compatible PHP 8 release.

**Comment by lcobucci** [comment]
Sure, but it's definitely good to keep them updated (IMHO)

**Comment by jensdenies** [comment]
@lcobucci Cool, thought so too! It just occurred to me while I was updating another package, haha.

**Pull request merged**
