### PR TITLE
Removed RequestHandlerRunner and replaced with RequestHandlerRunnerIn…

### LINKED ISSUE #114: Replace `RequestHandlerRunner` factory with `RequestHandlerRunnerInterface` factory
We have to remove the alias `RequestHandlerRunnerInterface` introduced in #110 and instead add it to the `factories`.
This should also remove the `RequestHandlerRunner` factory so that the `RequestHandlerRunner` service is not available via the container anymore.

This introduces a BC break but will provide better capabilities for projects which want to decorate the runner.

----
This can go to 3.11.x indeed, but we should change this from `aliases` to `factories` in 4.x since `RequestHandlerRunner` should not be requestable as a service from the container.

Since `delegators` only work on services, this would be a BC break for sure and therefore I'd like to keep this in mind and thus dropping it here. Creating a new issue for 4.x from this comment to keep track.

_Originally posted by @boesing in https://github.com/mezzio/mezzio/issues/110#issuecomment-1103748465_

### PR DESCRIPTION
**Pull request by mlussi90**
Removed the RequestHandlerRunner and replaced with RequestHanlderRunnerInterface  (#114)

### CODE REVIEW

**Comment by alexmerlin** [comment]
@mlussi90 Can you pick this up again?

**Comment by mlussi90** [comment]
@alexmerlin i rebased my branch against 4.0.x
is there something i can do in advance?

**Comment by alexmerlin** [comment]
IIRC, there were only a couple of files to be modified, after the rebase you have 171 files modified, with 10k lines added and 2k removed.
Maybe it would be better to start a new branch/PR with only the modifications relevant for this feature.
@gsteel what do you think?

**Comment by mlussi90** [comment]
@alexmerlin would be no problem to me to start a new branch/PR. Which branch should be the source/target branch?

**Comment by alexmerlin** [comment]
@mlussi90 from branch `4.0.x` into branch `4.0.x` because this feature is part of the `4.0.0` milestone.

**Pull request closed without merging**
