### PR TITLE
PHP 8.0 compatiblity and dependency upgrades.

### PR DESCRIPTION
**Pull request by jensdenies**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

This pull requests aims to make Mezzio PHP 8.0 compatible. I've bumped the dependencies to the **lowest** version that supports PHP 7.3 or higher. I'm not sure wether you would like to see the highest versions with at least PHP 7.3, if so, please let me know.

I've also upgraded PHPUnit to version > 8.5 and therefore I had to make some tests compatible. There are no test errors but there are over 50 warnings related to the deprecation and future removal of the `assertAttribute*` assertion methods.

### CODE REVIEW

**Comment by lcobucci** [comment]
@jensdenies I've got some time now, so I'll try to push another PR to help you with PHPUnit upgrade, then we can rebase this and make it 100% about PHP 8 compatibility :smile:

**Comment by jensdenies** [comment]
@lcobucci Thanks, as of #50 I'm currently implementing a polyfill trait for the `assertAttribute*` methods. Do you want to see that in a different PR too?

**Comment by jensdenies** [comment]
@lcobucci What workflow do you use to upgrade dependencies, do you prefer the lowest available version in composer for the supported PHP version or the highest?

**Comment by lcobucci** [comment]
@jensdenies we can rebase this one and move this forward!

I'd handle the update of each dependency in a separate commit of this PR, that allows us to ensure the CI tools work properly after every single change. That allows a good isolation IMHO.

After updating all dependencies I'd go about adding php8 support. 

But, again, I'm a control freak 🤣

**Comment by jensdenies** [comment]
@lcobucci I'll do it per commit, as you suggested, I like that. Maybe it's best to just start of on a fresh new branch, that makes things a little easier I suppose.

**Pull request closed without merging**
