### PR TITLE
Build `Application` with `RequestHandlerRunnerInterface` instead of `RequestHandlerRunner`, alias `RequestHandlerRunner` as `RequestHandlerRunnerInterface`

### PR DESCRIPTION
**Pull request by byan**
|    Q          |   A
|-------------- | ------
| BC Break      | no
| New Feature   | yes

### Description

Using interface-based dependence allows us to swtich the other implementations more easily.

### CODE REVIEW

**Comment by Ocramius** [comment]
This can go in `3.11.x`, but I see that the branch wasn't created 🤔

**Review by Ocramius — APPROVED** [review]
Thanks @byan! LGTM!

**Comment by boesing** [comment]
This can go to 3.11.x indeed, but we should change this from `aliases` to `factories` in 4.x since `RequestHandlerRunner` should not be requestable as a service from the container.

Since `delegators` only work on services, this would be a BC break for sure and therefore I'd like to keep this in mind and thus dropping it here. Creating a new issue for 4.x from this comment to keep track.

**Comment by Ocramius** [comment]
Rebased, thanks @byan!

**Pull request merged**
