### PR TITLE
Fix missing PSR HTTP Factory dependency

### PR DESCRIPTION
**Pull request by Firtzberg**
Signed-off-by: Hrvoje Jukic <hrcajuka@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Version [3.5.x](https://github.com/mezzio/mezzio/pull/75) introduces the class [Psr17ResponseFactoryTrait](https://github.com/mezzio/mezzio/blob/3.5.x/src/Container/Psr17ResponseFactoryTrait.php), which uses [ResponseFactoryInterface](https://github.com/php-fig/http-factory/blob/36fa03d50ff82abcae81860bdaf4ed9a1510c7cd/src/ResponseFactoryInterface.php) living in [PSR-17](https://github.com/php-fig/http-factory), but PSR-17 is not listed as a dependency in composer.json.
I have a project using Psr17ResponseFactoryTrait and it errors because the class ResponseFactoryInterface is not found. I solved this by temporarily including php-fig/http-factory as a dependency in my project, although none of my code uses it.

### CODE REVIEW

**Comment by Firtzberg** [comment]
I use composer 2, which explains those changes in composer.lock.
AFAIK composer.lock has no impact on users. Let me know if it bothers you

**Comment by Firtzberg** [comment]
ping

**Comment by boesing** [comment]
PSR-17 is not a hard requirement in mezzio v3 and thus should not be added as a dependency. 
As of v4, mezzio will only support PSR-17 and thus the dependency will be added. 
So as of no, I'd say nay to this change.

Please also note that you **should not** use the trait in your code as it is marked **internal**.
If your project uses the trait anyway, you should also ensure that you provide PSR-17 compatible factories. 

But maybe @weierophinney and/or @geerteltink has another view on this.

**Comment by geerteltink** [comment]
@boesing I'm not sure about this one. Even though it is not a requirement yet and can function without it, you are referencing the response factory interface. It kind of makes it a requirement even though it is used internal only. Why not add it in v3 if it will be required in v4 anyway?

**Comment by boesing** [comment]
@geerteltink I actually cannot see any use-case where this dependency could be missing.

If we add the dependency, all projects which do not need PSR-17 have a new dependency in their project which may be unused. If thats something we dont care about, feel free to merge this. Just wanted to point out that I dont see a reason why the trait should be used in upstream projects while not having a PSR-17 factory in place. Looks like the trait is used even tho no PSR-17 implementation is available.

So two problems:

1. internal trait used in upstream even tho it shouldnt
2. trait is used but no PSR-17 factory can be provided 🤷🏼‍♂️

**Comment by Firtzberg** [comment]
Maybe a bit of context will help making the right decision.

It took me quite some time to put the pieces together, I hope I got it right.
We have a Symfony DI container, which uses the configuration provided in https://github.com/mezzio/mezzio/blob/3.5.x/src/ConfigProvider.php#L64. `ServerRequestErrorResponseGeneratorFactory` as well as `NotFoundHandlerFactory` use the new trait relying on PSR-17. Both of them are part of the container configuration. We don't use either of them directly.
We don't use PSR-17, nor do we care about the implementation details of the the mentioned classes.
We can use the config provider on lower versions, but it breaks on 3.5.

**Comment by boesing** [comment]
Hm, I see. I guess this does not lead to errors in other projects as most of them use diactoros which then requires the dependency.

**Comment by boesing** [comment]
Thanks, @Firtzberg 
Release incoming.

**Comment by mbourquin** [comment]
Thanks i had the same issue. When i updated (composer update) a app from Mezzio 3.2.2 => 3.5.0 last week it no more worked. Now is fine with 3.5.1.

**Pull request merged**
