### PR TITLE
Fix quick start tutorial commands.

### PR DESCRIPTION
**Pull request by tyrsson**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR fixes the referenced commands in the Quick Start tutorial. The are missing the mezzio: namespace segment.

Tell us about why this change is necessary:
Just run any of the current commands as listed in the Mezzio quick start and they will fail. The docs are outdated to the point they do not reflect moving to the mezzio command namespace.

Related:
https://github.com/mezzio/mezzio/issues/146

Also out of date:
https://docs.mezzio.dev/mezzio/v3/reference/cli-tooling/

- Are you adding documentation?
  Just updating existing documentation

- Are you providing a QA improvement (additional tests, CS fixes, etc.) that
  does not change behavior?
  No

- Are you fixing a BC Break?
 No

- Are you adding something the library currently does not support?
  No

- Are you refactoring code?
  No

### CODE REVIEW

**Review by gsteel — CHANGES_REQUESTED** [review]
Did the images change in any meaningful way @tyrsson ? If not, could you revert changes to them and submit a commit containing only the changes to the markdown files please :)

**Comment by tyrsson** [comment]
That kinda had me scratching my head as well. The images showed modified from the moment I cloned it. Now that I think about it I know how to fix it but will need to check something first. I'll reply back as soon as I look at it later this morning.

**Comment by tyrsson** [comment]
There's nothing in the git attributes file to maintain them as binary. I'm pretty sure that's why they showed modified when I cloned it. I'll add it to my global and fix it later today.

**Comment by alexmerlin** [comment]
@tyrsson Did you manage to fix the issue with the images?

**Comment by tyrsson** [comment]
I will do that here in just a few minutes. Just going to ditch this one and reopen it. For some reason my local of this is not wanting to cooperate :(

**Pull request closed without merging**
